src/main/java/pl/javazaur/bean/ArticleBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.javazaur.bean;

import java.io.IOException;
import java.util.List;
import javax.faces.FacesException;
import javax.faces.bean.ManagedBean;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.validation.constraints.Size;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;
import org.springframework.web.servlet.ModelAndView;
import pl.javazaur.dao.AccountDao;
import pl.javazaur.dao.ArticleDao;
import pl.javazaur.pojo.Article;
import org.apache.log4j.Logger;

/**
 *
 * @author zico
 */
@Controller
@Scope("session")
@ManagedBean(name = "articleBean")
public class ArticleBean {

    //get log4j handler
    private static final Logger logger = Logger.getLogger(ArticleBean.class);
    
    @Autowired
    private ArticleDao articleDao;

    @Autowired
    private AccountDao accountDao;

    @Size(min = 1)
    private String content;
    @Size(min = 1, max = 120)
    private String title;

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    private String message;

    public String getMessage() {
        return message;
    }

    public Article getArticle(int id) {
        logger.debug("getArticle(" + id +")");
        Article article = articleDao.getArticle(id);
        if (article != null) {
            logger.debug("title: " + article.getTitle());
        }
        return article;
    }

    public List<Article> getAllArticles() {
        logger.debug("getAllArticles");
        return articleDao.getArticleList();
    }

    //clear form values
    private void clearForm() {
        setContent("");
        setTitle("");
    }

    /**
     * Creates a new instance of ArticleBean
     */
    public ArticleBean() {
        logger.debug("ArticleBean");
        clearForm();
    }
}

src/main/java/pl/javazaur/pojo/Article.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pl.javazaur.pojo;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author D
 */
@Entity
@Table(name = "ARTICLE")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Article.findAll", query = "SELECT a FROM Article a"),
    @NamedQuery(name = "Article.findById", query = "SELECT a FROM Article a WHERE a.id = :id"),
    @NamedQuery(name = "Article.findByTitle", query = "SELECT a FROM Article a WHERE a.title = :title"),
    @NamedQuery(name = "Article.findByAddDate", query = "SELECT a FROM Article a WHERE a.addDate = :addDate")})
public class Article implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "ID", nullable = false)
    private Integer id;
    @Size(max = 32700)
    @Column(name = "CONTENT", length = 32700)
    private String content;
    @Size(max = 150)
    @Column(name = "TITLE", length = 150)
    private String title;
    @Column(name = "ADD_DATE")
    @Temporal(TemporalType.TIMESTAMP)
    private Date addDate;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "articleId")
    private Collection<Comment> commentCollection;
    @JoinColumn(name = "AUTHOR", referencedColumnName = "LOGIN", nullable = false)
    @ManyToOne(optional = false)
    private Account author;

    public Article() {
    }

    public Article(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Date getAddDate() {
        return addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    @XmlTransient
    public Collection<Comment> getCommentCollection() {
        return commentCollection;
    }

    public void setCommentCollection(Collection<Comment> commentCollection) {
        this.commentCollection = commentCollection;
    }

    public Account getAuthor() {
        return author;
    }

    public void setAuthor(Account author) {
        this.author = author;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Article)) {
            return false;
        }
        Article other = (Article) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "pl.javazaur.pojo.Article[ id=" + id + " ]";
    }
    
}

src/main/java/pl/javazaur/controller/ArticleController.java
package pl.javazaur.controller;

import javax.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.SessionAttributes;
import org.springframework.web.servlet.ModelAndView;
import pl.javazaur.dao.AccountDao;
import pl.javazaur.dao.ArticleDao;
import pl.javazaur.pojo.Account;
import pl.javazaur.pojo.Article;

@Controller
@Transactional
@SessionAttributes
public class ArticleController {

    @Autowired
    private ArticleDao articleDao;
    @Autowired
    private AccountDao accountDao;

    //## INDEX | DETAILS SECTION ##\\
    @RequestMapping(value = "/article/*")
    public ModelAndView list() {
        return new ModelAndView("article/index", "articles", articleDao.getArticleList());
    }

    @RequestMapping(value = "/article/details/{articleId}**")
    public ModelAndView details(@PathVariable("articleId") int articleId) {

        return new ModelAndView("article/details", "articleId", articleId);
    }

    //## ADD SECTION ##\\
    @RequestMapping(value = "/article/add", method = RequestMethod.GET)
    public ModelAndView add() {
        return new ModelAndView("article/add", "command", new Article());
    }

    @RequestMapping(value = "/article/add", method = RequestMethod.POST)
    public String addArticle(
            @ModelAttribute("article") Article article,
            BindingResult result) {

        if (article.getContent().isEmpty() || article.getTitle().isEmpty()) {
            return "redirect:/article/add?error=1";
        }

//        Get user from spring security
        User user = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        String login = user.getUsername();
        Account author = accountDao.getAccount(login);

        article.setAuthor(author);

        articleDao.addArticle(article);

        return "redirect:index.htm";
    }

    //## EDIT SECTION ##\\
    @RequestMapping("/article/edit")
    public ModelAndView edit(HttpServletRequest request) {
        int id = Integer.parseInt(request.getParameter("id"));

        return new ModelAndView("edit", "editedArticle", articleDao.getArticle(id));
    }

    @RequestMapping(value = "/article/edit/{articleId}**", method = RequestMethod.GET)
    public ModelAndView edit(@PathVariable("articleId") int articleId) {
        return new ModelAndView("article/edit", "editedArticle", articleDao.getArticle(articleId));
    }

    @RequestMapping(value = "/article/edit/{articleId}**", method = RequestMethod.POST)
    public ModelAndView editArticle(@PathVariable("articleId") int articleId,
            @ModelAttribute("article") Article article,
            BindingResult result) {

        String redirection = "redirect:/article/edit/" + articleId + "?error=1";
        if (article.getContent().isEmpty() || article.getTitle().isEmpty()) {
            return new ModelAndView(redirection, "editedArticle", article);
        }

        articleDao.updateArticle(articleId, article.getContent());

        redirection = "redirect:/article/details/" + articleId;
        return new ModelAndView(redirection);
    }

    //## DELETE SECTION ##\\
    @RequestMapping("/article/delete/{articleId}**")
    public ModelAndView delete(@PathVariable("articleId") int articleId) {

        User user = (User) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
        String login = user.getUsername();

        String redirection;
        
        Article article = articleDao.getArticle(articleId);
        
        if (!login.equals(article.getAuthor().getLogin()))
            return new ModelAndView("article/delete_error");
            
        articleDao.deleteArticle(articleId);

        redirection = "redirect:/article/";
        
        return new ModelAndView(redirection);       
    }
}

src/main/webapp/WEB-INF/jsf/article/_article_add.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html">

    <form action="/javazaur/article/add" method="POST">
        <table>
            <tr>
                <td colspan="2">
                    <h:panelGroup rendered="#{request.getParameter('error') != null}">
                        <p class="error">Cannot add article with empty title or content</p>
                    </h:panelGroup>
                </td>
            </tr>
            <tr>
                <td>Title</td>
                <td><input size="103" type="text" value="#{article.title}" name="title"/></td>
            </tr>
            <tr>
                <td>Content</td>
                <td><textarea rows="20" cols="100" name="content">#{article.content}</textarea></td>
            </tr>
        </table>
        <input class="button" value="Add article" type="submit"/>
    </form>

</ui:composition>

src/main/webapp/WEB-INF/jsf/article/_article_details.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:rich="http://richfaces.org/rich"
                xmlns:f="http://java.sun.com/jsf/core">
    <h:outputStylesheet name="css/article.css"  />
    <h:outputStylesheet name="css/comment.css"  />
    <div class="article">
        <span class="title">
            #{article.title}
        </span>
        <div class="header-second">
            <span class="date">
                #{article.addDate}
            </span>
            <span class="author">
                #{article.author.login}
            </span>
        </div>
        <span class="content">
            #{article.content}
        </span>
        <div class="comments">
            <h:panelGroup rendered="#{not empty request.remoteUser}">
                <a href="/javazaur/comment/add/#{articleId}">Dodaj komentarz</a><Br />
            </h:panelGroup>
            <p><strong>Comments:</strong></p>
            <ui:repeat var="item" value="#{commentBean.getCommentsForArticle(articleId)}">
                <span class="comment">
                    <span class="comment-author">
                        <h:outputText value="#{item.addDate}"/>,
                        <h:outputText value="#{item.author.login}"/>                    
                    </span>
                    <span class="comment-message">
                        <h:outputText value="#{item.content}"/>                    
                    </span>
                </span>
            </ui:repeat>
        </div>
    </div>

</ui:composition>

src/main/webapp/WEB-INF/jsf/article/_article_edit.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets">
    <form action="/javazaur/article/edit/#{editedArticle.id}" method="POST">
        <table>
            <tr>
                <td>Here: #{editedArticle.id} :End</td>
            </tr>
            <tr>
                <td>Title</td>
                <td><input size="103" type="text" class="input-title" name="title" value="#{editedArticle.title}"/></td>
            </tr>
            <tr>
                <td>Content</td>
                <td><textarea rows="20" cols="100" class="input-content" name="content">#{editedArticle.content}</textarea></td>
            </tr>
        </table>
        <input class="button" value="Update article" type="submit"/>
    </form>

</ui:composition>

src/main/webapp/WEB-INF/jsf/article/add.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:f="http://java.sun.com/jsf/core">
    <body>
        <ui:composition template="/WEB-INF/jsf/templates/template.xhtml">
            <ui:define name="title">
                Articles
            </ui:define>
            <ui:define name="content-header">
                Add new article
            </ui:define>
            <ui:define name="content">
                <ui:include src="/WEB-INF/jsf/article/_article_add.xhtml" />
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/WEB-INF/jsf/article/details.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:f="http://java.sun.com/jsf/core">
    <body>
        <ui:composition template="/WEB-INF/jsf/templates/template.xhtml">
            <ui:param name="article" value="#{articleBean.getArticle(articleId)}" />
            <ui:define name="title">
                Article #{articleId} details
            </ui:define>
            <ui:define name="content-header">
                #{article.title}
            </ui:define>
            <ui:define name="content">
                <h:panelGroup rendered="#{not empty request.remoteUser and article.author.login == accountBean.userName}">
                    <a href="/javazaur/article/edit/#{articleId}">Edytuj artykuł</a><Br />
                    <a href="/javazaur/article/delete/#{articleId}">Usuń artykuł</a><Br />
                </h:panelGroup>
                <ui:include src="/WEB-INF/jsf/article/_article_details.xhtml" />                    
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/WEB-INF/jsf/article/edit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:f="http://java.sun.com/jsf/core">
    <body>
        <ui:composition template="/WEB-INF/jsf/templates/template.xhtml">
            <ui:define name="title">
                Articles
            </ui:define>
            <ui:define name="content-header">
                Edit article
            </ui:define>
            <ui:define name="content">
                <ui:include src="/WEB-INF/jsf/article/_article_edit.xhtml" />
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/WEB-INF/jsf/article/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:f="http://java.sun.com/jsf/core">
    <body>
        <ui:composition template="/WEB-INF/jsf/templates/template.xhtml">
            <ui:define name="title">
                Articles
            </ui:define>
            <ui:define name="content-header">
                List of articles
            </ui:define>
            <ui:define name="content">
                <h:outputStylesheet name="css/article.css"  />
                <ui:repeat var="item" value="#{articleBean.allArticles}">
                    <div class="article">
                        <span class="title">
                            #{item.title}
                        </span>
                        <div class="header-second">
                            <span class="date">
                                #{item.addDate}
                            </span>
                            <span class="author">
                                #{item.author.login}
                            </span>
                        </div>
                        <span class="content">
                            #{item.content}
                        </span>
                        <h:outputLink value="details/#{item.id}">Show comments</h:outputLink>
                    </div>
                </ui:repeat>
            </ui:define>
        </ui:composition>
    </body>
</html>